apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-11-11T05:53:41Z"
  generation: 1
  labels:
    app: fairnessdistributionalgorithm-server
  name: fairnessdistributionalgorithm-server
  namespace: default
  resourceVersion: "27997"
  uid: 3dda3209-38d5-4616-b0c1-7e1ea252ec6a
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: fairnessdistributionalgorithm-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fairnessdistributionalgorithm-server
    spec:
      containers:
      - image: chinesebooster99/fairnessdistributionalgorithm-server
        imagePullPolicy: Always
        name: fairnessdistributionalgorithm-server
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-11-11T05:53:50Z"
    lastUpdateTime: "2023-11-11T05:53:50Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-11-11T05:53:41Z"
    lastUpdateTime: "2023-11-11T05:53:50Z"
    message: ReplicaSet "fairnessdistributionalgorithm-server-86554c9fff" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1